HBTQ is the more common acronomy in Sweden and I+ is just to be more …
code4recovery/spec pull request #73
Opened 2023-09-26 16:17 UTC by tiptop96

…inclusive

2023-09-26 16:21 UTC, tim-rohrer commented
Hi Gus, Let's discuss this at our next meeting. Thanks.

2023-09-27 15:26 UTC, tiptop96 commented
Hey! Unfortunately I am unable to join on 10/7, is there any chance we could discuss it here?

2023-10-07 21:14 UTC, joshreisner requested changes
please make `HBTQ` - `HBTQIAA+` is still part of the proposal but will progress separately

2023-10-08 15:32 UTC, joshreisner approved these changes

2023-10-08 15:32 UTC, merged